messaging:
  broker:
    hosts: localhost:9092
  consumer:
    session-timeout-ms: 10000
    offset-reset: earliest
    max-poll-interval-ms: 10000
    poll-timeout-ms: 1000
  topics:
    - names: musics
      group: musics-grp
      consumer-number: 1
    - names: artists
      group: artists-grp
      consumer-number: 1